version: '3'
services:
#  postgres:
#    image: 'postgres:latest'
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: postgres_password

  redis:
    container_name: ${COMPOSER_PROJECT_NAME}_redis
    image: 'redis:latest'
    ports:
      - 63791:6379


  mysql:
    container_name: ${COMPOSER_PROJECT_NAME}_mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
#    volumes:
#      - ./var/mysql-data:/var/lib/mysql
    ports:
      - 33063:3306

  nginx:
    restart: always
    container_name: ${COMPOSER_PROJECT_NAME}_nginx
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - api
      - client

  api:
    container_name: ${COMPOSER_PROJECT_NAME}_api
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
    - /app/node_modules
    - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
#      - PGUSER=postgres
#      - PGHOST=postgres
#      - PGDATABASE=postgres
#      - PGPASSWORD=postgres_password
#      - PGPORT=5432
      - mysqlUSER=root
      - mysqlHOST=mysql
      - mysqlDATABASE=mydb
      - mysqlPASSWORD=password
      - mysqlPORT=3306
    depends_on:
      - redis
#      - postgres
      - mysql

  client:
    container_name: ${COMPOSER_PROJECT_NAME}_client
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
    - /app/node_modules
    - ./client:/app

  worker:
    stdin_open: true
    container_name: ${COMPOSER_PROJECT_NAME}_worker
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
    - /app/node_modules
    - ./worker:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080